name: AzLink
version: 1.0.0
main: Azuriom\AzLink\PocketMine\AzLinkPM
api: 5.0.0
src-namespace-prefix: Azuriom\AzLink\PocketMine
website: https://azuriom.com
decription: The plugin to link your Azuriom website with your server.
author: Azuriom Team

extensions: [curl]

permissions:
  azlink.admin:
    description: Allows you to use the /azlink command.
    default: op
